version: '3.4'
services:
  keycloak:
    image: jboss/keycloak:latest
    hostname: keycloak
    environment:
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_LOGLEVEL=INFO
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      #- KEYCLOAK_IMPORT=/tmp/realm.json
      - DB_VENDOR=mysql
      - MYSQL_ADDR=mysql
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=keycloak
      - DB_PORT=3306
    volumes:
      - ${PWD}/realm-export.json:/tmp/realm.json
      - ${PWD}/keycloak/themes/sciex:/opt/jboss/keycloak/themes/sciex
    networks:
      transit_idp:
    depends_on:
      - mysql
    labels:
      - traefik.backend=keycloak
      - traefik.enable=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:localhost;PathPrefix:/auth
      - traefik.protocol=http
    command: ["-b", "0.0.0.0", "-Dkeycloak.profile.feature.docker=enabled"]

  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - "./docker/volumes/mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      transit_idp:

  traefik:
    image: traefik:v1.7.4-alpine
    hostname: localhost
    environment:
      TZ: America/Toronto
    depends_on: 
      - keycloak
    ports:
    - "80:80"
    - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      --logLevel='DEBUG'
      --api.dashboard=true
      --InsecureSkipVerify=true
      --entryPoints='Name:http Address::80'
      --entryPoints='Name:https Address::443 TLS'
      --defaultentrypoints='http,https'
      --docker
      --docker.exposedbydefault=true
      --docker.watch=true
      --docker.swarmmode=false
      --docker.endpoint='unix:///var/run/docker.sock'
    networks:
      transit_idp:
      transit_ttyd:
    labels:
      traefik.enable: true
networks:
  transit_idp:
    external: true
  transit_ttyd:
    external: true